config/routes.rb
Musicstore::Application.routes.draw do
  root :to => 'musics#index'
  resources :musics
end

app/models/music.rb
class Music < ActiveRecord::Base
  attr_accessible :name, :description, :price, :song

  validates_presence_of :name, :price, :song

  #paperclip
  has_attached_file :song,
    :storage => :s3,
    :s3_credentials => {
      :bucket => ENV['AWS_BUCKET'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    },
    :path => "/:filename"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  def index
    @musics = Music.all
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(params[:music])
    respond_to do |format|
      if @music.save
        format.html { redirect_to musics_path }
      end
    end
  end

  def destroy
    @music = Music.find(params[:id])
    respond_to do |format|
      if @music.destroy
        format.html { redirect_to musics_path }
      end
    end
  end

  def edit
    @music = Music.find(params[:id])
  end

  def update
    @music = Music.find(params[:id])
    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to musics_path }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <%= link_to 'Add Song', new_music_path, :data => { :'loading-text' => 'button' } %>
  <%= yield %>
</div>

</body>
</html>

app/views/musics/edit.html.erb
<h1>Edit Song</h1>
<%= form_for @music, :html => { :multipart => true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :song %>
  <%= f.file_field :song %><br/><br/>
  <%= f.submit %>
<% end %>

app/views/musics/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Sample</th>
    </tr>
  </thead>
  <tbody>
  <% @musics.each do |f| %>
    <tr>
      <td><%= f.name %></td>
      <td><%= f.description %></td>
      <td>$<%= f.price %></td>
      <td><%= audio_tag(f.song, :autoplay => false, :controls => true, :preload => 'auto') %></td>
      <td><%= link_to 'Edit', edit_music_path(f), :class => 'btn btn-success' %></td>
      <td><%= button_to 'Destroy', music_path(f), :class => 'btn btn-danger', :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/musics/new.html.erb
<h1>Add Song</h1>
<%= form_for @music, :html => { :multipart => true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :song %>
  <%= f.file_field :song %><br/><br/>
  <%= f.submit %>
<% end %>